### ISSUE TITLE
Skunk Works project to read .json file.

### ISSUE THREAD

**Issue by Charlie110** [ucsb-cs56-webapps/ucsb-cs56-gauchocourses#3]
Professor Conrad provides the .json files contain courses data. 
Make some java code that read the json file data into arraylist ot hash map of course object.
Include good test coverage.

**Comment by Charlie110** [comment]
Approved 400 points

**Comment by NellyNi** [comment]
json github repo url: [https://github.com/ucsb-cs56-m18/ucsb-cs56-gauchocourses-sw1.git]
